name: 'Version Bump on Release'
description: 'Automatically bump version after release for Swift packages and Xcode apps'
author: 'intrusive-memory'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  bump-type:
    description: 'Version bump type: major, minor, or patch'
    required: false
    default: 'minor'
  main-branch:
    description: 'Name of the main branch'
    required: false
    default: 'main'
  development-branch:
    description: 'Name of the development branch'
    required: false
    default: 'development'
  project-type:
    description: 'Project type: swift-package, xcode-app, or auto'
    required: false
    default: 'auto'

outputs:
  old-version:
    description: 'Previous version before bump'
    value: ${{ steps.bump.outputs.old-version }}
  new-version:
    description: 'New version after bump'
    value: ${{ steps.bump.outputs.new-version }}
  pr-url:
    description: 'URL of the created pull request'
    value: ${{ steps.create-pr.outputs.pr-url }}

runs:
  using: 'composite'
  steps:
    - name: Checkout main branch (source of truth)
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.main-branch }}
        fetch-depth: 0

    - name: Ensure development branch exists
      shell: bash
      run: |
        # Configure Git for potential branch creation
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Fetch all branches
        git fetch origin

        # Check if development branch exists remotely
        if git ls-remote --heads origin ${{ inputs.development-branch }} | grep -q ${{ inputs.development-branch }}; then
          echo "âœ“ Development branch exists remotely"
        else
          echo "Development branch does not exist. Creating from ${{ inputs.main-branch }}..."
          git checkout -b ${{ inputs.development-branch }}
          git push -u origin ${{ inputs.development-branch }}
          echo "âœ“ Created development branch from ${{ inputs.main-branch }}"
        fi

    - name: Checkout development branch
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.development-branch }}
        fetch-depth: 0

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Rebase development onto main (main is source of truth)
      shell: bash
      run: |
        echo "================================================"
        echo "REBASING DEVELOPMENT ONTO MAIN"
        echo "Main branch is the source of commit truth"
        echo "================================================"

        # Fetch latest main to ensure we have the most recent commits
        echo "Fetching latest ${{ inputs.main-branch }}..."
        git fetch origin ${{ inputs.main-branch }}

        # Show current state before rebase
        echo "Current branch: $(git branch --show-current)"
        echo "Commits on development not in main:"
        git log --oneline origin/${{ inputs.main-branch }}..HEAD || echo "  (none)"

        # Rebase development onto main - main is the source of truth
        # This ensures development is based on the latest main commits
        echo "Rebasing ${{ inputs.development-branch }} onto origin/${{ inputs.main-branch }}..."
        git rebase origin/${{ inputs.main-branch }}

        # Verify rebase was successful
        echo "âœ“ Rebase complete"
        echo "Development is now based on main"
        echo "Base commit: $(git merge-base HEAD origin/${{ inputs.main-branch }})"
        echo "================================================"

    - name: Detect project type
      id: detect
      shell: bash
      run: |
        PROJECT_TYPE="${{ inputs.project-type }}"

        if [ "$PROJECT_TYPE" = "auto" ]; then
          # Auto-detect based on project files
          if [ -f "Package.swift" ] && [ -f "README.md" ]; then
            PROJECT_TYPE="swift-package"
          elif find . -maxdepth 3 -name "*.xcodeproj" -o -name "*.xcworkspace" | grep -q .; then
            PROJECT_TYPE="xcode-app"
          else
            echo "Error: Could not auto-detect project type"
            exit 1
          fi
        fi

        echo "type=$PROJECT_TYPE" >> $GITHUB_OUTPUT
        echo "Detected project type: $PROJECT_TYPE"

    - name: Bump version
      id: bump
      shell: bash
      env:
        PROJECT_TYPE: ${{ steps.detect.outputs.type }}
        BUMP_TYPE: ${{ inputs.bump-type }}
      run: |
        if [ "$PROJECT_TYPE" = "swift-package" ]; then
          ${{ github.action_path }}/scripts/bump-swift-package.sh
        elif [ "$PROJECT_TYPE" = "xcode-app" ]; then
          ${{ github.action_path }}/scripts/bump-xcode-app.sh
        else
          echo "Error: Unknown project type: $PROJECT_TYPE"
          exit 1
        fi

    - name: Commit version bump
      shell: bash
      run: |
        git add -A
        git commit -m "chore: Bump version to ${{ steps.bump.outputs.new-version }} after release ${{ github.event.release.tag_name }}

        Automated version bump following release ${{ github.event.release.tag_name }}.
        Previous version: ${{ steps.bump.outputs.old-version }}
        New version: ${{ steps.bump.outputs.new-version }}
        Bump type: ${{ inputs.bump-type }}
        Project type: ${{ steps.detect.outputs.type }}

        ðŸ¤– Generated by GitHub Actions"

    - name: Push to development
      shell: bash
      run: |
        # Force push because we rebased development onto main
        git push --force-with-lease origin ${{ inputs.development-branch }}

    - name: Create pull request
      id: create-pr
      shell: bash
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        PR_BODY="## Automated Version Bump

        This PR contains an automated version bump following the publication of release **${{ github.event.release.tag_name }}**.

        ### Changes

        - **Previous version**: ${{ steps.bump.outputs.old-version }}
        - **New version**: ${{ steps.bump.outputs.new-version }}
        - **Bump type**: ${{ inputs.bump-type }}
        - **Project type**: ${{ steps.detect.outputs.type }}
        - **Release**: ${{ github.event.release.tag_name }}
        - **Release URL**: ${{ github.event.release.html_url }}

        ### Files Updated

        $(git diff HEAD~1 --name-only | sed 's/^/- /')

        ### What's Next

        After this PR is merged, future development work will be based on version ${{ steps.bump.outputs.new-version }}.

        ðŸ¤– Automated by GitHub Actions"

        echo "Attempting to create pull request..."

        if PR_URL=$(gh pr create \
          --base ${{ inputs.main-branch }} \
          --head ${{ inputs.development-branch }} \
          --title "chore: Bump version to ${{ steps.bump.outputs.new-version }}" \
          --body "$PR_BODY" 2>&1); then
          echo "pr-url=$PR_URL" >> $GITHUB_OUTPUT
          echo "âœ“ Pull request created: $PR_URL"
        else
          echo "âš ï¸  Could not create pull request automatically"
          echo "Error: $PR_URL"
          echo ""
          echo "This is likely due to GitHub Actions permissions."
          echo "The version bump was successful - please create the PR manually:"
          echo ""
          echo "  Branch: ${{ inputs.development-branch }} â†’ ${{ inputs.main-branch }}"
          echo "  Title: chore: Bump version to ${{ steps.bump.outputs.new-version }}"
          echo ""
          echo "Or run: gh pr create --base ${{ inputs.main-branch }} --head ${{ inputs.development-branch }}"
          echo "pr-url=" >> $GITHUB_OUTPUT
        fi
